name: tuneup
description: A command-line tool to manipulate and inspect your Dart projects.

# This version must be updated in tandem with the lib/tuneup.dart version.
version: 0.3.1
author: Devon Carew <devoncarew@google.com>
homepage: https://github.com/google/tuneup.dart

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  analysis_server_lib: 0.1.0
  analyzer: '>=0.29.0 <0.31.0'
  args: '>=0.12.0 <0.14.0'
  intl: ^0.15.0
  logging: ^0.11.0
  path: '>=1.4.0 <2.0.0'
  quiver: ^0.24.0
  yaml: '>=2.0.0 <3.0.0'

dev_dependencies:
  html: ^0.13.0
  test: ^0.12.0

# Add the bin/tuneup.dart script to the scripts pub installs.
executables:
  tuneup:
